# Generated by Django 2.2.8 on 2019-12-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default=None, max_length=250)),
                ('fecha', models.IntegerField()),
                ('clasificacion', models.CharField(max_length=3)),
                ('duracion', models.IntegerField()),
                ('genero', models.CharField(max_length=150)),
                ('director', models.CharField(max_length=150)),
                ('actores', models.CharField(max_length=800)),
                ('sipnosis', models.TextField()),
                ('idioma', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('caratula', models.ImageField(upload_to='')),
            ],
        ),
    ]
