# Generated by Django 2.2.8 on 2019-12-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personajes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=None, max_length=128)),
                ('nombre_real', models.CharField(max_length=128)),
                ('foto', models.ImageField(upload_to='')),
                ('sexo', models.BooleanField()),
            ],
        ),
    ]
